name: dot_weather
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  location: ^7.0.0
  current_location: ^0.0.3
  dio: ^5.6.0
  google_fonts: ^4.0.4
  cached_network_image: ^3.3.1
  xdg_status_notifier_item: ^0.0.1
  flutter_launcher_icons: ^0.13.1
  geolocator: ^13.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/day.jpg
    - assets/day1.jpg
    - assets/night.jpg
    - assets/night1.jpg
    - assets/moring.jpg
    - assets/moring1.jpg
    - assets/sunset.jpg
    - assets/sunset1.jpg
    - assets/dot-weather.png
